Questao 11
n1 = int(input("Digite um número:"))
n2 = int(input("Digite um número:")) 
n3 = float(input("Digite um número real:"))
v1 = ((n1*2) * (n2/2))
v2 = ((n1*3) + (n3*3))
v3 = (n3**3)
print("O produto do dobro do primeiro com a metade do segundo é {:.0f}".format(v1))
print("A soma do triplo do primeiro com o terceiro é {}".format(v2))
print("O terceiro elevado ao cubo é {}".format(v3))